config/routes.rb
# Instances
resources :projects do
  resources :password_instances, shallow: true
end
match 'password_instances/:id/data_schema', :to => 'password_instances#data_schema', :via => [:get]


resources :password_templates, :only => [:index,:show]
get 'password_templates/:id/form', :to => 'password_templates#form'

app/models/password_instance.rb
class PasswordInstance < ActiveRecord::Base
  unloadable

  belongs_to :password_template
  belongs_to :project

  attr_accessible :name, :data, :password_template_id, :parent_id
  attr_encrypted :data_plain, :key => :get_secret, :attribute => 'data_encrypted'

  # Unique names on project scope
  validates :name, :uniqueness => {:scope => :project_id}
  validates_length_of :name, :minimum => 3
  # Only allow a-z0-9_
  validates_format_of :name, :with => /\A[a-z0-9\-_]+\Z/, :message => l(:validate_only_small_alphanumeric_underscore)

  # Needs project_id
  validates :project, :presence => true
  validates :password_template, :presence => true

  # data validation
  validate :validate_data

  # Nested set of instances order by name
  acts_as_nested_set :order => :name, :dependent => :destroy


  # Path to secrets file
  @@secrets_file = File.expand_path(File.dirname(__FILE__) + "../../../config/password_tool_secret.yml")

  # Get classes for the password_instance tree
  def css_classes
    s = 'project'
    s << ' root' if root?
    s << ' child' if child?
    s << (leaf? ? ' leaf' : ' parent')
    s
  end

  def get_secret
    PasswordInstance.get_secret
  end

  # Get hash of data
  def data
    JSON.parse(data_plain)
  end

  def data=(val)
    data_plain=JSON.generate(val)
  end

  def validate_data
    if not password_template.nil?
      result = password_template.data_validate(data_plain)
      if not (result['errors'].length == 1 and result['errors']['__global'].length == 0)
        errors.add(:data_plain, result['errors'])
      end
    end
  end

  # Get json tree of data and schema
  def data_schema_json
    JSON.generate(data_schema)
  end

  # Get tree of data and schema
  def data_schema
    password_template.schema_obj.data_schema(data_plain)
  end

  # Recalculates all lft and rgt values based on password instances name
  def self.rebuild_tree!
    transaction do
      update_all "lft = NULL, rgt = NULL"
      rebuild!(false)
    end
  end

  # Yields the given block for each password_instance with its level in the tree
  def self.password_instance_tree(password_instances, &block)
    ancestors = []
    password_instances.sort_by(&:lft).each do |password_instance|
      while (ancestors.any? && !password_instance.is_descendant_of?(ancestors.last))
        ancestors.pop
      end
      yield password_instance, ancestors.size
      ancestors << password_instance
    end
  end

  def validate_data_plain_json_parseable
    if data_plain.present?
      begin
        JSON.parser(data_plain)
      rescue JSON::ParserError
        errors.add(:data, "json_unparseable")
      end
    end
  end


  def self.get_secret
    YAML.load(File.open(@@secrets_file))['secret']
  end


  def self.create_secret

    # Check that no secrets exists
    begin
      secret = get_secret
    rescue Exception => e
      secret = nil
    end

    if secret.nil?

      if PasswordInstance.count > 0
        # Already existing PasswordInstances

        raise "Can't create secret, because there is at least a existing password entry"

      else
        # No instance exists
        puts "Generate a secret key"

        secret={
            'secret' => SecureRandom.base64(128)
        }

        # Write file
        File.write(@@secrets_file, secret.to_yaml)

        # Only owner rights
        File.chmod(0600, @@secrets_file)

      end


    else
      raise "Secret already existing"
    end

  end

end

app/controllers/password_instances_controller.rb
class PasswordInstancesController < ApplicationController

  include PasswordInstancesHelper

  default_search_scope :password_instances
  model_object PasswordInstance
  before_filter :find_project_by_project_id, :only => [:index, :new, :create]
  before_filter :find_model_object, :except => [:index, :new, :create]
  before_filter :find_project_from_association, :except => [:index, :new, :create]
  before_filter :authorize

  before_filter :find_password_instance, :except => [ :index, :new, :create]
  before_filter :find_password_instances, :only => [ :index, :new, :create, :edit, :update ]

  def index
  end

  def set
  end


  # Show @password_instance
  def show

  end

  # Show @password_instance's data_schema
  def data_schema
  end

  # Edit @password_instance
  def edit
  end

  def update
    @password_instance.update_attributes(params[:password_instance])
    @password_instance.data_plain = JSON.generate(params[:password_instance]['data'])

    if @password_instance.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to action: 'index', :project_id => @project.identifier
    else
      render :action => 'edit'
    end
  end

  # Delete @password_instance
  def destroy
    project_identifier = @password_instance.project.identifier
    @password_instance.destroy
    respond_to do |format|
      format.html { redirect_to action: 'index', :project_id => project_identifier}
      format.api  { render_api_ok }
    end
  end

  def create
    @password_instance = PasswordInstance.new (params[:password_instance])
    @password_instance.data_plain = JSON.generate(params[:password_instance]['data'])
    @password_instance.project = @project

    if @password_instance.save
      # Save succeed
      respond_to do |format|
        format.html {
          flash[:notice] = l(:notice_successful_create)
          redirect_to action: 'index'
        }
        format.api  { redirect_to action: 'index'}
      end
    else
      # Validation error
      respond_to do |format|
        format.html { render :action => 'new'}
        format.api  { render_validation_errors(@password_instance) }
      end
    end
  end

  def new
    @password_instance = PasswordInstance.new
  end
end

app/helpers/password_instances_helper.rb
module PasswordInstancesHelper

  # Find password_instance_ids
  def find_password_instance
    @password_instance = PasswordInstance.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_password_instances
    @password_instances = PasswordInstance.where(["project_id = ?", @project.id])
  end


  def password_instance_tree_options(password_instances)
    s = [["<#{l(:label_pt_root)}>",nil]]
    PasswordInstance.password_instance_tree(password_instances) do |password_instance, level|
      name_prefix = (level > 0 ? '&nbsp; ' * 2 * level + '&#187; ' : '').html_safe
      tag_options = {:value => password_instance.id}
      s << ["#{name_prefix}#{password_instance.name} (#{password_instance.password_template.name})".html_safe, password_instance.id]
    end
    s
  end





end

app/views/password_instances/_form.html.erb
<%= error_messages_for 'password_instance' %>

<div class="box tabular">
  <p><%= f.select :password_template_id, options_for_select(PasswordTemplate.template_options_for_form,@password_instance.password_template_id),{}, :onchange => 'changedPasswordInstanceTemplate(this)'  %></p>
  <p><%= f.select :parent_id, options_for_select( password_instance_tree_options(@password_instances),@password_instance.parent_id),{:label => :label_pt_parent}, :disabled => true  %></p>
  <p><%= f.text_field :name, :required => true, :label => :label_pt_name, :disabled => true %></p>
</div>

<% if params[:action] == "create" or params[:action] == "edit" %>
<script type="text/javascript">
    $(document).ready(function() {
    initPasswordInstanceForm(<%= @password_instance.password_template.schema_obj.form_json(@password_instance.data_plain).html_safe %>)
    });
</script>
<% end %>

app/views/password_instances/data_schema.js.erb
<%= @password_instance.data_schema_json.html_safe %>

app/views/password_instances/edit.html.erb
<h2><%=l(:label_passwort_instance)%></h2>

<%= labelled_form_for @password_instance, { :html => {:class => 'password_instance_form'}}  do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>
    <p><%= submit_tag l(:button_save) %></p>
<% end %>

app/views/password_instances/index.html.erb
<div class="contextual">
<% if User.current.allowed_to?({ controller: "password_instances", action: "new" },@project) -%>
      <%= link_to l(:label_password_instance_new), { controller: "password_instances", action: "new" }, class: 'icon icon-add' %>
<% end -%>
  <%= link_to l(:label_pt_show_all), "#", onclick:"showPasswordInstanceAllContent()", class: 'icon icon-unlock' %>
  <%= link_to l(:label_pt_hide_all), "#", onclick:"hidePasswordInstanceAllContent()", class: 'icon icon-lock' %>
</div>

<h2><%=l(:label_password_instances)%></h2>


<%# Register JS Event Listener -%>
<%= javascript_tag do -%>
    // Listen to show/hide events
    $(document).ready(function() {

        $('a.pw-hide').click(togglePasswordInstanceContent);
        $('a.pw-show').click(togglePasswordInstanceContent);

    });
<% end -%>


<%#= @password_instances %>

<div class="autoscroll">
  <table class="list pw-table">
    <thead><tr>
      <th><%=l(:label_pt_name)%></th>
      <th><%=l(:field_password_template)%></th>
      <th><%=l(:label_pt_data) %></th>
      <th><%=l(:field_updated_on)%></th>
      <th><%=l(:field_created_on)%></th>
      <th></th>
    </tr></thead>
    <tbody>
    <% PasswordInstance.password_instance_tree(@password_instances) do |pw_instance, level| %>
        <tr class="<%= cycle("odd", "even") %> <%= pw_instance.css_classes %> <%= level > 0 ? "idnt idnt-#{level}" : nil %>">
          <td class="name"><span><%= link_to pw_instance.name, { controller: "password_instances", action:"show", id: pw_instance.id } %></span></td>
          <td><%= pw_instance.password_template.name %></td>
          <td width="500px">
            <%= link_to(l(:button_show), "##{pw_instance.id}", :class => 'icon icon-unlock pw-show') %>
            <%= link_to(l(:button_hide), "##{pw_instance.id}", :style => 'display:none;', :class => 'icon icon-lock pw-hide') %>
          </td>
          <td align="center"><%= format_time(pw_instance.updated_on) %></td>
          <td align="center"><%= format_time(pw_instance.created_on) %></td>
          <td class="buttons">
            <% if User.current.allowed_to?({ controller: "password_instances", action: "edit" },@project) -%>
                <%= link_to(l(:button_edit), { controller: "password_instances", action:"edit", id: pw_instance.id}, :class => 'icon icon-edit') %>
            <% end -%>
            <% if User.current.allowed_to?({ controller: "password_instances", action: "destroy" },@project) -%>
              <%= link_to(l(:button_delete),
                { controller: "password_instances", action:"destroy", id: pw_instance.id},
                :method => :delete,
                :class => 'icon icon-del',
                :data => { :confirm => l(:text_pt_instance_destroy_warning,"#{pw_instance.name} (#{pw_instance.password_template.name})")}
              ) %>
            <% end -%>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<%=  %>

<% html_title(l(:label_project_plural)) -%>

app/views/password_instances/new.html.erb
<h2><%=l(:label_password_instance_new)%></h2>

<%= labelled_form_for @password_instance, {:url => project_password_instances_path(@project), :html => {:class => 'password_instance_form'}}  do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>
    <p><%= submit_tag l(:button_create) %></p>
<% end %>

app/views/password_instances/set.html.erb
<h2>GitlabConnectionsController#set</h2>

app/views/password_instances/show.html.erb
<h2>Password: <%= @password_instance.name %></h4>

<div class="box tabular">
  <pre><%=@password_instance.data%></pre>
</div>